### ISSUE TITLE
Missing libunistring.so file after build libunistring

### ISSUE THREAD

**Issue by ghost** [venomlinux/ports#2813]
After build libunistring it makes a `ln /usr/lib/libunistring.so /usr/lib/libunistring.so.5` and to `libunistring.so.5.0.0` too but is needed one symblic link more of `/usr/lib/libunistring.so` to `/usr/lib/libunistring.so.2` (`ln /usr/lib/libunistring.so /usr/lib/libunistring.so.2`)

Package link here: https://github.com/venomlinux/ports/tree/repos/main/libunistring

**Comment by emmett1** [comment]
Why you need `libunistring.so.2` library?

**Comment by ghost** [comment]
> Why you need `libunistring.so.2` library?
curl no works without it for some reason.

**Comment by emmett1** [comment]
Not working mean error about missing shared library? If this case just run `revdep -r` to rebuild to link against new library.

**Comment by ghost** [comment]
> Not working mean error about missing shared library? 

Yes

> If this case just run `revdep -r` to rebuild to link against new library.

i tried it but no matters if i rebuild it. the package dont make the link

**Comment by emmett1** [comment]
Alright. Give me log or anything about the error. And how to reproduce it.

**Comment by Visone-Selektah** [comment]
> > Not working mean error about missing shared library?
> 
> Yes
> 
> > If this case just run `revdep -r` to rebuild to link against new library.
> 
> i tried it but no matters if i rebuild it. the package dont make the link

What pkg do you rebuild? libunistring or curl?

**Comment by ghost** [comment]
> 

libunistring but curl needed that shared library it to work

**Comment by ghost** [comment]
> Alright. Give me log or anything about the error. And how to reproduce it.

ok here are the install logs
https://notes.anonpaste.org/?07c98ed137570589#Aj5W3n6owtRZ2WwEjoERZUgCEMGAKcaqaRrRbQ6WCggz

To reproduce it is just install the package because it dont make that link to the shared library by default

**Comment by emmett1** [comment]
curl working fine for me without libunistring. And i dont see other distros curl need libunistring. Without any error log, i cant do anything.

**Comment by ghost** [comment]
> curl working fine for me without libunistring. And i dont see other distros curl need libunistring. Without any error log, i cant do anything.

Ok i found the bug happens after run scratch sysup. And here a video cuz my pc is going to die if i download obs
Edit: maybe it going to take a while to upload it becouse github don’t want to

**Comment by ghost** [comment]
https://youtu.be/6H6Ek8JcX8E
Here is!

**Comment by emmett1** [comment]
Ok thanks for the video. 

I understand now, latest update of libunistring provide new library named `.so.5` instead of `.so.2` that caused broken shared lib of `curl`. This should be solve by rebuild `curl` to link against new library, this is how linux works, when new library provided, the program that use it should be rebuild to use new library, not by manually creating symlink to old library. I believe this is how all distros exist in the world works. 

Ok this is how you do it in venom, the proper way;
1- fetch curl source
`# scratch install -ro curl`
2- upgrade system/libunistring (i believe this caused broken curl)
`portsync && scratch sysup`
3- i think this is when curl is broken, so rebuild curl (basically run `revdep -r` should fix it automatically but you said still failed)
`# scratch install -fr curl`

Thats all, curl should works fine now. If it still broken just tell me.

Btw do you have irc or telegram so i can assist you fast, not waiting days or weeks for your reply. If it takes days or weeks i'm afraid i forgotten about your issue.

Thanks

**Comment by ghost** [comment]
it isn't fixed yet because more packages like libsoup needed
> Btw do you have irc or telegram so i can assist you fast, not waiting days or weeks for your reply. If it takes days or weeks i'm afraid i forgotten about your issue.

So I'm going to the irc

**Comment by ghost** [comment]
it just fixed itself idk how
